### ISSUE TITLE
Blocking self-updates

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.wire.WireDesktop#10]
Currently, the AppImage(?) self-updates still work (sucessfully). In order to be able of controlling the application version solely via `flatpak`, I think it would be best to block that behaviour.

If this is really due to AppImage, maybe there also are other AppImage specific bit still in the package, which could be removed for a clean build? Maybe its also the application itself, then I don’t know what to do best, here…

**Comment by x80486** [comment]
AFAIK, `Wire` can be updated/upgraded in two ways:

- Wrapper version — thus it is, the `.tar.gz`, `.AppImage`, Flatpak `.deb` file(s)
- Web version — the inline updates (or sort of)

I think this is better explained in [How do Wire updates work?](https://support.wire.com/hc/en-us/articles/115001919905-How-do-Wire-updates-work-).

I haven't tested if you can do a silent wrapper update, but I would say that's not possible since the Flatpak is read-only. I'll test it in future versions.

Let me know if you were referring to something else.

**Comment by fbruetting** [comment]
So the update appeared in the app for me, I clicked on it and it seemed to update itself, as I got no Wire update via `flatpak update` since. This is not optimal, as the system (and the administrator) should be in control of the versions. If apps update themselves, they circumvent the application management of `flatpak`. See for example the blog post [here](https://blogs.gnome.org/mclasen/2018/08/02/on-flatpak-updates).

**Comment by x80486** [comment]
There is a [new update](https://medium.com/@wireupdates/) for the wrapper: `3.5.2881`, but the Flatpak is currently on `3.4.2879`. Are you able to see the _blue bar_ on the top for updating the application? I don't see it, and that's what I'm expecting to happens.

The in-place updates are only for the Web part, which I don't control. The same happens with other software vendors, they do like to push those tiny updates rather than packaging the whole thing every time, for instance: SmartGit, SmartSynchronize, Postman, etc.

**Comment by fbruetting** [comment]
![bildschirmfoto von 2019-01-08 22-01-16](https://user-images.githubusercontent.com/10520767/50861328-922ead00-1398-11e9-8453-b1d670866ba5.png)

Current version is: 3.5.2881 – 2019.01.02.1310

**Comment by x80486** [comment]
The latest version for the Web is `2019.01.08.1320`; that's why you are getting that blue ribbon since you are at `2019.01.02.1310`. If you say `YES`, it will be updated _in place_; if you close the application (as with <kbd>Ctrl + Q</kbd>, or alternatively, using the menu option `Wire | Quit Wire`) it will also be updated automatically.

The wrapper (`3.5.2881`) is not updated until a new version is released and the Flatpak manifest is updated.

**Comment by fbruetting** [comment]
Ah, now I see.
