### ISSUE TITLE
Right click - insert doesn't work while ctrl+v does.

### ISSUE THREAD

**Issue by mielouk** [flathub/com.wire.WireDesktop#18]
Flatpak 1.3.3 Wire 3.9.2895

The rest of my specs: https://8n1.org/15102/7f50

When copying a text I'm not able to insert it via right click - insert.
Although ctrl+v works as intended.

**Comment by x80486** [comment]
I have two instances (Arch Linux `4.19.37-1-lts #1 SMP Sat Apr 27 10:16:32 CEST 2019 x86_64 GNU/Linux` and Silverblue `30`) running GNOME `3.32`...but I can't replicate that.

Also, you don't specify how or from where are you copying, so I would assume the issue is system-wide, with any possible way you can employ to copy text (in general).

1. Have you tried an older version?
1. Did you try the AppImage (same and/or different version)
1. What about other apps? – more specifically Electron-based ones

Sometimes the copy and paste ceremony gets weird (at least on GNOME) for me also, but it mostly happens with the `Terminal`.

If you try those things first and still get the same result I would try to install some distro with `Cinnamon` and give it a whirl to see if I can replicate this.

**Comment by mielouk** [comment]
Thx for the answer.

No, it is not a system-wide problem. It usually works fine, even in the terminal (Terminology), otherwise I wouldn't have created this bug report.
Usually I copy something from a file or a website into Wire. When I try to copy something from the history of the conversation in Wire via right click - copy, it works just fine and the marked text can be pasted everywhere else, except back in Wire via right click. Be it a link or text it can be pasted everywhere I need it to be.

1. I've heard that flatpak offers the option to install different versions since a few weeks ago, but I've never used it before. If you can tell me how to do this I'll happily do it.

2. Just "installed" the AppImage, which had the same version as my flatpaked one and the right click insert worked.

3. Not sure which other apps use Electron. Some time ago I installed/compiled(?) something with it, but I can't remember what it was.

Don't know whether it is related to Arch, Cinnamon or flatpak.

**Comment by x80486** [comment]
I follow this for downgrading: https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading

And again, just to make (double and triple) sure, the issue is that you copy stuff from somewhere (using any method), and then you do right-click and select `Paste` in Wire...but it doesn't do anything, right?

Can you try this:

```shell
$ sudo flatpak override --nosocket=wayland com.wire.WireDesktop
$ sudo flatpak override --show com.wire.WireDesktop
```

...make sure you can see something like:
```shell
# [Context]
# sockets=!wayland;
```

...then run the app: `flatpak run com.wire.WireDesktop` and try the copy and paste stuff. Finally run `sudo flatpak override --reset com.wire.WireDesktop` to rollback all of that.

I just installed Fedora Cinnamon `30` and `flatpak` `1.2.4`, but still, I can copy and paste stuff left and right in any way I want – using the shortcuts and the mouse (via the right-click stuff).

**Comment by mielouk** [comment]
That is absolutely correct! The only perceivable change is that the blinking cursor stops blinking until I left-click into the same line again, after the failed paste.

I did what you said and the result was the same. Right click insert doesn't work in Wire.

**Comment by x80486** [comment]
@mielouk, I installed a couple of other distributions in Boxes, but still, the copy and paste stuff works. I'm going to wait for somebody else to chime in and give me some other details, so maybe I can get to the same state you are in right now.

I see all the events being triggered for copy/paste and mouse clicks – starting `Wire` with `flatpak run com.wire.WireDesktop --devtools --enable-logging --inspect`

**Comment by mielouk** [comment]
Thank you for your effort.

I don't get much out of the devtool, but this is the CLI output for the command you mentioned. 

https://8n1.org/15117/0c5d

This problem is not a big deal. I only want Wire (or any flatpak app for that matter) to work good out of the box for everybody. Hopefully someone else has the same problem and does share it with us. It's also possible that it is an isolated problem on my end. We will see. Thx again!

**Comment by x80486** [comment]
@mielouk, there has been a couple of updates since you had this issue. Do you still have the <kbd>Ctrl V</kbd> problem?

**Comment by mielouk** [comment]
@x80486 Sorry to report that I'm still not able to insert via right click. Ctrl+V works just fine.

**Comment by x80486** [comment]
Are you still using `Arch Linux Cinnamon 4.0.10`?

**Comment by mielouk** [comment]
Arch Linux with Cinnamon 4.4.4 and sway master. It's present in the DE and the WM.

**Comment by x80486** [comment]
You are right, it doesn't work, somehow, with `Cinnamon`.

I'm shocked, this behaves accordingly in all the other Linux versions I've tried. If you have some time, read on [through this issue](https://github.com/wireapp/wire-desktop/issues/3012/) (from the official repo) and let me know if it sounds about the same thing that happens to you. In that case, you can subscribe to that issue instead of this one.

**Comment by mielouk** [comment]
Yes, it sounds exactly the same. I just didn't realize that it pastes it in the other account. Thank you!
Shall I close this flathub issue?

**Comment by x80486** [comment]
I think it makes sense to close it since it's something I cannot fix in the Flatpak package...and again, you should subscribe and possibly give any input on the "other side", if there is anything else you might want to add.

**Comment by mielouk** [comment]
Closed, as this is not probably not related to flatpak and there is a duplicate which already got mentioned by @x80486
