### ISSUE TITLE
Closing the application leaves everything running

### ISSUE THREAD

**Issue by fbruetting** [flathub/com.wire.WireDesktop#8]
After closing the application, all five processes remain running and the tray icon also still remains.

**Comment by x80486** [comment]
Are you talking about closing the application, as in clicking the window's <kbd>X</kbd> icon?

While running as a Flatpak there are always `5` processes (`wire-desktop`) and another one: `bwrap` for the sandbox. If I don't press <kbd>Ctrl + Q</kbd>, or alternatively, use the menu option `Wire | Quit Wire`, all those processes never go away; and it's quite similar while running as an AppImage (only tested on my Fedora VM) – I haven't tested the `.deb` approach/install.

<a href="https://ibb.co/GQrVt1X"><img src="https://i.ibb.co/qY2RW4z/Screenshot-from-2018-12-01-14-44-47.png" alt="Screenshot-from-2018-12-01-14-44-47" border="0"></a>

If so, as far as I can tell, that's the expected behavior. The application window is sometimes hidden and sometimes closed – peek into the conversation for wireapp/wire-desktop/issues/1821. Moreover, you can verify that by executing the Flatpak through the command-line and closing (as in clicking the <kbd>X</kbd> icon for) the application window: you never get the prompt back. Good thing is, if the machine is killed or restarted abruptly, the application is not stucked on that weird state as before :crossed_fingers:

On the other hand, I believe I ran into issues while upgrading when it was getting into that weird state issue (#1), so I remember I had to do:

- `pkill -f wire`
- `rm -rf ~/.var/app/com.wire.WireDesktop/`

...to make all those processes go away (for good) because there were a previous set hanging around at that time due to the issue.

Whenever `Wire` finally fixes this appropriately (the aforementioned issue **1821**), I will try to delete the `env TMPDIR=$XDG_CACHE_HOME/tmp` and see if it finally works.

**Comment by fbruetting** [comment]
Ok, commented upstream.
